"""Change media column to ARRAY

Revision ID: 7a5e055239d5
Revises: ab2b091d3434
Create Date: 2024-09-24 16:35:13.653729

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "7a5e055239d5"
down_revision: Union[str, None] = "ab2b091d3434"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "tweets", sa.Column("my_array", sa.ARRAY(sa.Integer()), nullable=True)
    )
    op.drop_column("tweets", "media")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "tweets", sa.Column("media", sa.INTEGER(), autoincrement=False, nullable=True)
    )
    op.drop_column("tweets", "my_array")
    # ### end Alembic commands ###
