"""Change media column to ARRAY

Revision ID: 9ae5e9c38924
Revises: 3517e503af2f
Create Date: 2024-09-24 16:00:42.689549

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "9ae5e9c38924"
down_revision: Union[str, None] = "3517e503af2f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
