"""Change media column to ARRAY

Revision ID: ab2b091d3434
Revises: 9ae5e9c38924
Create Date: 2024-09-24 16:33:50.328675

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "ab2b091d3434"
down_revision: Union[str, None] = "9ae5e9c38924"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
