TEST_USER_DATA = [
    ("Eduard", "Komarov", "themswesson", "test"),
    ("Jane", "Smith", "jane.smith456", "test2"),
    ("Robert", "Johnson", "robert.john789", "test3"),
    ("Emily", "Davis", "emily_dav234", "test4"),
    ("Michael", "Brown", "michael_bro890", "test5"),
    ("Sarah", "Wilson", "sarah.wil567", "test6"),
    ("David", "Miller", "david_mil012", "test7"),
    ("Laura", "Moore", "laura.moo890", "test8"),
    ("James", "Taylor", "james_tay678", "test9"),
    ("Emma", "Anderson", "emma.and456", "test10"),
    ("William", "Thomas", "will_thom234", "test11"),
    ("Olivia", "Jackson", "olivia_jac901", "test12"),
    ("Daniel", "White", "daniel_whi567", "test13"),
    ("Sophia", "Harris", "sophia.har123", "test14"),
    ("Matthew", "Martin", "matthew_mar234", "test15"),
    ("Ava", "Martinez", "ava.mar901", "test16"),
    ("Elijah", "Clark", "elijah_cla567", "test17"),
    ("Isabella", "Rodriguez", "isabella_rod123", "test18"),
    ("Ethan", "Lewis", "ethan_lew456", "test19"),
    ("Mia", "Walker", "mia.wal789", "test20"),
]

TEST_TWEETS_DATA = [
    "The future belongs to those who code.",
    "Coding is my therapy. #PythonLife",
    "Keep calm and code on!",
    "Coffee + Python = Productivity.",
    "Debugging is like being a detective in a crime movie.",
    "Eat, sleep, code, repeat.",
    "Writing code is my superpower.",
    "Code is poetry, and Python is my pen.",
    "Always be learning. #Pythonista",
    "Automation makes life easier. #PythonRocks",
    "Turning coffee into code since day one.",
    "Coding: The only superpower I need.",
    "In code we trust. #PythonForLife",
    "Error 404: Social life not found. #CodeAllDay",
    "Learning Python is like learning magic.",
    "Just a coder living in a digital world.",
    "Code today, conquer tomorrow.",
    "Stay curious. Keep coding. #PythonJourney",
    "One line of code at a time. #Progress",
    "Python: The language of the future.",
    "Challenge accepted. #PythonCoder",
    "Code is art. #TechCreativity",
    "The best way to predict the future is to code it.",
    "Python makes everything possible.",
    "Another day, another bug squashed.",
    "Mastering the art of code. #PythonMaster",
    "Keep calm and import Python.",
    "If at first you don't succeed, try another code block.",
    "Python isn't just a language, it's a way of life.",
    "Simple code. Big impact. #PythonPower",
    "Coding is thinking in loops and functions.",
    "Learning Python one error at a time.",
    "There's no place like localhost.",
    "Working smarter, not harder with Python.",
    "Life's better when you're coding.",
    "Good code is its own reward.",
    "Solving problems, one line at a time. #Python",
    "Python: Because typing less means doing more.",
    "Nothing beats the joy of a program that works.",
    "Every line of code is a step closer to greatness.",
]
